name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install .NET MAUI
      run: dotnet worload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build TokenCounter.csproj -c Release -f net6.0-android --no-restore
